module.exports = {
  apps: [
    {
      name: 'marymatelier',
      script: './server.js',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        DB_HOST: 'localhost',
        DB_PORT: 5432,
        DB_NAME: 'marymatelier',
        DB_USER: 'app',
        DB_PASSWORD: 'Marym2026',
        DB_SSL: 'true',
        API_URL: 'http://45.128.223.242',
        CORS_ORIGIN: 'http://45.128.223.242',
        VITE_API_URL: 'http://45.128.223.242',
        LOG_LEVEL: 'info',
      },
      error_file: './logs/error.log',
      out_file: './logs/out.log',
      merge_logs: true,
      max_memory_restart: '1G',
      watch: false,
      ignore_watch: ['node_modules', 'dist', 'logs'],
      exp_backoff_restart_delay: 100,
    },
  ],
};
