/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const DEFAULT = 'en';

const TRANSLATIONS = {
  ar: {
    catalog: {
      searchLabel: 'ابحثي عن فستان',
      searchPlaceholder: 'ابحثي بالاسم أو الكود أو الوصف',
      brandTitle: 'ايجار فساتين فاخرة',
      brandSubtitle: 'جاهزة للارتداء',
      heroEyebrow: 'Shop by Occasion',
      heroHeadline: 'فساتين زفاف لاشهر المصممين وافخم التصاميم',
      heroDescription: 'اكتشفي مجموعة فساتين أنيقة وفريدة مُختارة بعناية، مع تصميمات تناسب كل مناسبة بدءاً من السهرة إلى الزفاف.',
      shopNow: 'تسوقي الآن',
      discover: 'اكتشفي التشكيلة',
      statsDresses: 'فساتين حصرية',
      statsSupport: 'دعم الواتساب',
      statsReturn: 'استرجاع سهل',
      sectionByOccasion: 'تصفحي حسب المناسبة',
      sort: {
        label: 'ترتيب حسب',
        default: 'الافتراضي',
        priceAsc: 'السعر: من الأقل للأعلى',
        priceDesc: 'السعر: من الأعلى للأقل'
      },
      categories: {
        mermaid_extension: 'ميرميد باكستنشن',
        big_size:  'Plus Size',
        mermaid_full_skirt: 'ميرميد بسكيرت كاملة',
        one_look: 'لوك واحد',
        all: 'كل الفساتين'
      },
      viewAll: 'عرض الكل',
      featured: 'تشكيلة الفساتين المميزة',
      faqsTitle: 'الأسئلة الشائعة',
      faqsIntro: 'إليكن الإجابات على الأسئلة المتكررة حول الإيجار والخدمة.',
      faqQuestionLabel: 'السؤال',
      faqAnswerLabel: 'الإجابة',
      showCount: (n) => `عرض ${n} فستان`,
      showMore: 'عرض المزيد',
      footerVisit: 'زورينا في أتيليه MaryMatelier',
      developedBy: 'Developed By AAM-Tech',
      footerCopy: 'أرقى خدمات تصميم المواقع والانظمة.خدمة روابط الواتساب الفورية.',
      contact: 'اتصلي بنا',
      about: 'عن المتجر',
      faq: 'الأسئلة الشائعة',
      footerNote: '2026 ©AAM-Tech',
    },
    product: {
      prevImage: 'الصورة السابقة',
      nextImage: 'الصورة التالية',
      available: 'متوفر',
      unavailable: 'محجوز',
      availableBadge: '● متوفر للإيجار',
      unavailableBadge: '● غير متوفر',
      ctaSchedule: 'حجز موعد قياس بالأتيليه',
      ctaContinue: 'متابعة التسوق',
      trustPickup: 'استلام من الأتيليه',
      trustConfirm: 'تأكيد الحجز عبر الواتساب',
      trustFlexible: 'إيجار يومي مرن',
      notePrebook: 'هذا حجز مبدئي. لضمان حجز الفستان في يوم مناسبتكِ، يرجى إتمام التأكيد داخل الأتيليه.',
      sectionDescription: 'وصف المنتج',
      sectionSpecs: 'مواصفات المنتج',
      backToStore: 'العودة للمتجر',
      notFoundTitle: 'الفستان غير موجود',
    },
    admin: {
      loginTitle: 'تسجيل دخول المشرف',
      loginSubtitle: 'أدخلي الرمز السري للوصول إلى لوحة التحكم.',
        loginButton: 'دخول للوحة التحكم',
        loginError: 'رمز الدخول غير صحيح! يرجى المحاولة مرة أخرى.',
        whatsappTestSuccess: 'تم إرسال رسالة تجريبية بنجاح! تحققي من واتساب.',
        whatsappTestFail: 'فشل إرسال الرسالة التجريبية.',
        conflictReserved: (date) => `عذراً، هذا الفستان محجوز بالفعل في ${date}.`,
        confirmButNotifyFail: 'تم تأكيد الحجز، لكن تعذّر إرسال إشعار واتساب.',
        resendSuccess: 'تم إعادة إرسال إشعار التأكيد للمشرف بنجاح.',
        resendFail: 'تعذّر إعادة إرسال إشعار التأكيد. تأكدي من إعداد متغيرات WhatsApp.',
      quickLinks: 'اختصارات سريعة',
      overview: 'نظرة عامة',
      reservations: 'طلبات الحجز',
      dresses: 'إدارة الفساتين',
      dressManagement: 'إدارة الفساتين',
      addNewDress: 'إضافة فستان جديد',
      settings: 'إعدادات واتساب API',
      addDress: 'إضافة فستان',
      totalReservations: 'إجمالي الحجوزات',
      totalDresses: 'إجمالي الفساتين',
      pendingReservations: 'الحجوزات المعلقة',
      confirmedReservations: 'الحجوزات المؤكدة',
      pending: 'معلقة',
      confirmed: 'مؤكدة',
      confirmDelete: 'هل أنتِ متأكدة من رغبتكِ في حذف هذا الفستان نهائياً؟',
      confirmDeleteFaq: 'هل أنتِ متأكدة من رغبتكِ في حذف هذا السؤال؟',
      moveTop: 'نقل إلى الأعلى',
      moveUp: 'نقل للأعلى',
      moveDown: 'نقل للأسفل',
      moveTopShort: 'أعلى',
      backToStore: 'خروج للمتجر',
      status: 'الحالة',
      actions: 'إجراءات',
      edit: 'تعديل',
      delete: 'حذف',
      client: 'العميل',
      dress: 'الفستان',
      rentDate: 'تاريخ الإيجار',
      trialDate: 'تاريخ القياس',
      brandPill: 'Admin',
      brandSubtitle: 'لوحة التحكم',
      passcodeLabel: 'رمز الدخول السري *',
      passcodePlaceholder: 'مثال: 1234',
      metrics: {
        totalDresses: 'إجمالي الفساتين',
        availableDresses: 'متوفر للحجز',
      },
      settingsInfo: {
        serverStatusTitle: 'حالة الخادم',
        serverStatusHint: 'تحقق من وجود متغيرات بيئة WhatsApp على الخادم.',
        serverCheckFail: 'فشل التحقق من الخادم',
        checkServerButton: 'تحقّق من حالة الخادم',
        whatsappTestButton: 'إرسال رسالة تجريبية',
        whatsappTestingText: 'جاري الإرسال...',
      },
      defaultSortLabel: 'ترتيب المتجر الافتراضي',
      save: 'حفظ',
      defaultSortSaved: 'تم الحفظ',
      saveFail: 'فشل الحفظ',
      search: 'بحث...',
      all: 'الكل',
      confirm: 'تأكيد',
      confirmed: 'مؤكدة',
      resendNotify: 'إعادة إرسال إشعار',
      noReservations: 'لا توجد طلبات حجز حتى الآن.',
      noMatches: 'لا توجد نتائج تطابق البحث.',
      dressTableDress: 'الفستان',
      dressTableCode: 'كود',
      dressTableCategory: 'التصنيف',
      dressTableRent: 'الإيجار',
      dressTableSize: 'المقاس',
      dressTableStatus: 'الحالة',
      dressTableFeatured: 'مميزة',
      dressTableActions: 'إجراءات',
      settingsTitle: 'إعدادات واتساب API',
      settingsCredentials: 'بيانات اعتماد Meta WhatsApp',
      settingsHint1: 'يُستخدم WhatsApp API فقط من متغيرات البيئة في Vercel:',
      settingsHint2: 'WHATSAPP_ACCESS_TOKEN و WHATSAPP_PHONE_NUMBER_ID و WHATSAPP_ADMIN_NUMBER و WHATSAPP_SALES_NUMBER.',
      settingsHint3: 'لا يتم استخدام أي بيانات اعتماد محلية في واجهة المشرف أو من خلال التخزين المحلي.',
        langLabel: 'اللغة',
        faqs: 'الأسئلة الشائعة',
        addFaq: 'أضف سؤال',
        noFaqs: 'لا توجد أسئلة شائعة بعد.',
    },
    sales: {
      loginTitle: 'تسجيل دخول المبيعات',
      loginSubtitle: 'أدخلي الرمز السري للوصول إلى لوحة المبيعات.',
      loginButton: 'دخول للوحة المبيعات',
      loginError: 'رمز الدخول غير صحيح! يرجى المحاولة مرة أخرى.',
      dashboardTitle: 'لوحة المبيعات',
      dashboardSubtitle: 'يمكنك تأكيد أو حذف الطلبات هنا.',
      passcodeLabel: 'رمز الدخول السري *',
      passcodePlaceholder: 'مثال: 1234',
      brandPill: 'المبيعات',
      pending: 'طلبات قيد الانتظار',
      confirmed: 'الطلبات المؤكدة',
      noReservations: 'لا توجد طلبات لعرضها.',
      backToStore: 'العودة للمتجر',
      confirmSuccess: 'تم تأكيد الحجز بنجاح.',
      confirmFail: 'تعذّر تأكيد الحجز. حاول مرة أخرى.',
      deleteSuccess: 'تم حذف الطلب بنجاح.',
      deleteFail: 'تعذّر حذف الطلب. حاول مرة أخرى.',
    },
    whatsapp: {
      title: 'حجز موعد القياس',
      trialCostText: 'تكلفة تجربة الفستان 100 ج.م لكل فستان',
      success: 'تم إرسال طلبك بنجاح! وصل إشعار واتساب للأتيليه وسنتواصل معكِ لتأكيد الموعد.',
      errorSave: '❌ خطأ في حفظ الحجز. تأكدي من اتصالك بالإنترنت وحاولي مرة أخرى.',
      errorGeneric: 'تعذّر إرسال طلبك. حاول مرة أخرى.',
      fullName: 'الاسم بالكامل *',
      namePlaceholder: 'مثال: نورا أحمد',
      phone: 'رقم الهاتف *',
      phonePlaceholder: '01012345678',
      weight: 'الوزن (كجم)',
      weightPlaceholder: 'مثال: 60',
      height: 'الطول (سم)',
      heightPlaceholder: 'مثال: 165',
      trialDate: 'تاريخ تجربة القياس *',
      rentDate: 'تاريخ الإيجار المرغوب *',
      time: 'الوقت المفضل للقياس *',
      notes: 'ملاحظات إضافية (اختياري)',
      notesPlaceholder: 'أي تفاصيل إضافية...',
      sending: 'جاري إرسال الطلب...',
      confirm: 'تأكيد وحجز الموعد',
      dateBlockedMessagePrefix: 'الفستان',
      dateBlockedHint: 'يرجى اختيار تاريخ إيجار آخر أو التواصل مع الأتيليه.',
      dateBlockedOk: 'حسناً، سأختار تاريخاً آخر',
    },
    form: {
      addDressTitle: 'إضافة فستان جديد',
      editDressTitle: 'تعديل بيانات الفستان',
      codeLabel: 'كود الفستان المميز *',
      nameLabel: 'اسم الفستان (بالعربية) *',
      designerLabel: 'اسم المصمم *',
      categoryLabel: 'التصنيف *',
      priceLabel: 'سعر الإيجار اليومي (ج.م) *',
      sizeLabel: 'المقاس *',
      colorLabel: 'اللون *',
      imagesLabel: 'صور الفستان *',
      detailsLabel: 'تفاصيل ووصف الفستان *',
      addButton: 'إضافة الفستان للقائمة',
      saveButton: 'حفظ التعديلات',
      cancel: 'إلغاء',
      addDesigner: 'أضف',
      designerPlaceholder: '-- اختر مصمم --',
      errorFill: 'يرجى ملء جميع الحقول المطلوبة (بما في ذلك اسم المصمم) وإضافة صورة واحدة على الأقل.',
      duplicateId: 'كود الفستان هذا مستخدم بالفعل لفستان آخر، يرجى كتابة كود فريد.',
      availabilityLabel: 'حالة توافر الفستان:',
      availableText: 'متاح للإيجار الفوري',
      unavailableText: 'محجوز / غير متوفر',
      featuredLabel: 'عرض الفستان في قسم العرض المميز:',
      featuredText: 'عرض مميز في البطاقة الخارزة',
      notFeaturedText: 'عدم العرض المميز',
      removeImageTitle: 'حذف الصورة',
      placeholders: {
        code: 'مثال: DRS-005',
        name: 'مثال: فستان كحلي مطرز سواريه',
        price: 'مثال: 1500',
        color: 'مثال: كحلي داكن / فضي',
        imagesUploadHint: 'اضغطي لتحديد صورة أو أكثر من جهازك',
        addDesignerPrompt: 'أدخلي اسم المصمم',
      },
      sizeOptions: {
        S: 'S (صغير)',
        M: 'M (متوسط)',
        L: 'L ( كبير )',
        XL: 'XL (كبير جداً)',
        XXL: 'XXL (ضخم)'
      },
      bigSizeLabel: 'مقاس كبير',
      bigSizeHint: 'علّمي هذا الخيار للفستان ليظهر في فلتر المقاسات الكبيرة',
      imagesUploadLabel: 'تحميل صور الفستان',
    }
    ,
    cart: {
      addToCart: 'أضف إلى السلة',
      empty: 'السلة فارغة',
      items: 'قطع',
      maxReached: 'يسمح بتجربة 4 فساتين كحد أقصى في اليوم',
      maxAllowedText: 'الحد الأقصى المسموح لتجربة الفساتين في اليوم هو 4 فساتين'
    },
    qrModal: {
      title: 'احفظي أكواد QR',
      subtitle: 'لتجربة القياس في الأتيليه',
      instruction: 'احفظي أكواد QR التالية وأظهريها عند الوصول للأتيليه لبدء قياس كل فستان مباشرة',
      downloadOne: 'حفظ',
      downloadAll: 'حفظ جميع الأكواد',
      done: 'تم',
    },
  },
  en: {
    catalog: {
      searchLabel: 'Search dresses',
      searchPlaceholder: 'Search by name, code or description',
      brandTitle: 'RENTAL LUXURY DRESSES',
      passcodeLabel: 'Passcode *',
      passcodePlaceholder: 'e.g. 1234',
      brandPill: 'Sales',
      brandSubtitle: 'READY TO WEAR',
      heroEyebrow: 'Shop by Occasion',
      heroHeadline: 'Shine on your big night with LUXURIOUS dresses by talented hands',
      heroDescription: 'Discover a curated collection of elegant and unique dresses for every occasion, from evening gowns to bridal dresses.',
      shopNow: 'Shop Now',
      discover: 'Discover Collection',
      statsDresses: 'Exclusive Dresses',
      statsSupport: 'WhatsApp Support',
      statsReturn: 'Easy Returns',
      sectionByOccasion: 'Browse by Occasion',
      sort: {
        label: 'Sort by',
        default: 'Default',
        priceAsc: 'Price: Low to High',
        priceDesc: 'Price: High to Low'
      },
        categories: {
          mermaid_extension: 'Mermaid (with extension)',
          big_size: 'Plus Size',
          mermaid_full_skirt: 'Mermaid (full skirt)',
          one_look: '1 Look',
          all: 'All dresses'
        },
      viewAll: 'View All',
      featured: 'Featured Dresses',
      faqsTitle: 'FAQ',
      faqsIntro: 'Answers to frequently asked questions about renting and services.',
      faqQuestionLabel: 'Question',
      faqAnswerLabel: 'Answer',
      showCount: (n) => `Showing ${n} dresses`,
      showMore: 'Show more',
      footerVisit: 'Visit MaryMatelier Atelier',
      developedBy: 'Developed By AAM-Tech',
      footerCopy: 'Premium web & systems design services. Instant WhatsApp links.',
      contact: 'Contact Us',
      about: 'About',
      faq: 'FAQ',
      footerNote: '2026 ©AAM-Tech',
    },
    product: {
      prevImage: 'Previous image',
      nextImage: 'Next image',
      available: 'Available',
      unavailable: 'Unavailable',
      availableBadge: '● Available to rent',
      unavailableBadge: '● Not available',
      ctaSchedule: 'Book measurement appointment',
      ctaContinue: 'Continue shopping',
      trustPickup: 'Pick up from atelier',
      trustConfirm: 'WhatsApp confirmation',
      trustFlexible: 'Flexible daily rent',
      notePrebook: 'This is a provisional reservation. To guarantee the dress on your date please confirm in the atelier.',
      sectionDescription: 'Product description',
      sectionSpecs: 'Product specifications',
      backToStore: 'Back to shop',
      notFoundTitle: 'Dress not found',
    },
    admin: {
      loginTitle: 'Admin Login',
      loginSubtitle: 'Enter passcode to access the dashboard.',
        loginButton: 'Enter Dashboard',
        loginError: 'Invalid passcode, please try again.',
        whatsappTestSuccess: 'Test message sent successfully! Check WhatsApp.',
        whatsappTestFail: 'Failed to send test message.',
        conflictReserved: (date) => `Sorry, this dress is already reserved on ${date}.`,
        confirmButNotifyFail: 'Reservation confirmed but failed to send WhatsApp notification.',
        resendSuccess: 'Confirmation notification resent to admin successfully.',
        resendFail: 'Failed to resend confirmation notification. Check WhatsApp env variables.',
      quickLinks: 'Quick Links',
      overview: 'Overview',
      reservations: 'Reservations',
      dresses: 'Manage Dresses',
      dressManagement: 'Dress Management',
      addNewDress: 'Add New Dress',
      settings: 'WhatsApp API Settings',
      addDress: 'Add Dress',
      totalReservations: 'Total Reservations',
      totalDresses: 'Total Dresses',
      pendingReservations: 'Pending Reservations',
      confirmedReservations: 'Confirmed Reservations',
      pending: 'Pending',
      confirmed: 'Confirmed',
      status: 'Status',
      actions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      client: 'Client',
      dress: 'Dress',
      rentDate: 'Rent Date',
      trialDate: 'Trial Date',
      confirmDelete: 'Are you sure you want to permanently delete this dress?',
      confirmDeleteFaq: 'Are you sure you want to delete this FAQ?',
      moveTop: 'Move to top',
      moveUp: 'Move up',
      moveDown: 'Move down',
      moveTopShort: 'Top',
      brandPill: 'Admin',
      brandSubtitle: 'Dashboard',
      passcodeLabel: 'Passcode *',
      passcodePlaceholder: 'e.g. 1234',
      metrics: {
        totalDresses: 'Total dresses',
        availableDresses: 'Available for rent',
      },
      settingsInfo: {
        serverStatusTitle: 'Server status',
        serverStatusHint: 'Check for WhatsApp environment variables on the server.',
        serverCheckFail: 'Server health check failed',
        checkServerButton: 'Check server status',
        whatsappTestButton: 'Send test message',
        whatsappTestingText: 'Sending...',
      },
      defaultSortLabel: 'Default catalog sort',
      save: 'Save',
      defaultSortSaved: 'Saved',
      saveFail: 'Save failed',
      search: 'Search...',
      all: 'All',
      confirm: 'Confirm',
      confirmed: 'Confirmed',
      resendNotify: 'Resend notification',
      noReservations: 'No reservations yet.',
      noMatches: 'No matching results found.',
      dressTableDress: 'Dress',
      dressTableCode: 'Code',
      dressTableCategory: 'Category',
      dressTableRent: 'Rent',
      dressTableSize: 'Size',
      dressTableStatus: 'Status',
      dressTableFeatured: 'Featured',
      dressTableActions: 'Actions',
      settingsTitle: 'WhatsApp API Settings',
      settingsCredentials: 'Meta WhatsApp credentials',
      settingsHint1: 'WhatsApp API is only used from Vercel environment variables:',
      settingsHint2: 'WHATSAPP_ACCESS_TOKEN, WHATSAPP_PHONE_NUMBER_ID, WHATSAPP_ADMIN_NUMBER, WHATSAPP_SALES_NUMBER.',
      settingsHint3: 'No local credentials are used in the admin interface or through local storage.',
      langLabel: 'Language',
        faqs: 'FAQs',
      backToStore: 'Back to Store',
        addFaq: 'Add FAQ',
        noFaqs: 'No FAQs yet.',
    },
    form: {
      addDressTitle: 'Add New Dress',
      editDressTitle: 'Edit Dress',
      codeLabel: 'Dress Code *',
      nameLabel: 'Dress Name (AR) *',
      designerLabel: 'Designer *',
      categoryLabel: 'Category *',
      priceLabel: 'Daily Rent (EGP) *',
      sizeLabel: 'Size *',
      colorLabel: 'Color *',
      imagesLabel: 'Dress Images *',
      detailsLabel: 'Dress details & description *',
      addButton: 'Add Dress',
      saveButton: 'Save Changes',
      cancel: 'Cancel',
      addDesigner: 'Add',
      designerPlaceholder: '-- Select designer --',
      errorFill: 'Please fill all required fields (including designer name) and add at least one image.',
      duplicateId: 'This dress code is already in use, please enter a unique code.',
      availabilityLabel: 'Dress availability:',
      availableText: 'Available for immediate rent',
      unavailableText: 'Reserved / Unavailable',
      featuredLabel: 'Display in featured section:',
      featuredText: 'Featured display in hero card',
      notFeaturedText: 'Do not feature',
        placeholders: {
          code: 'e.g. DRS-005',
          name: 'e.g. Navy beaded evening gown',
          price: 'e.g. 1500',
          color: 'e.g. Deep navy / Silver',
          imagesUploadHint: 'Click to select one or more images from your device',
          addDesignerPrompt: 'Enter designer name',
        },
        sizeOptions: {
          S: 'S (Small)',
          M: 'M (Medium)',
          L: 'L (Large)',
          XL: 'XL (Extra Large)',
          XXL: 'XXL'
        },
        bigSizeLabel: 'Big size',
        bigSizeHint: 'Mark as big size (shows in Big Size filter)',
        imagesUploadLabel: 'Upload dress images',
    }
    ,
    cart: {
      addToCart: 'Add to cart',
      empty: 'Your cart is empty',
      items: 'items',
      maxReached: 'Only 4 dresses are allowed to be tried in a day',
      maxAllowedText: 'Maximum allowed dresses to try in one day: 4'
    },
    qrModal: {
      title: 'Save Your QR Codes',
      subtitle: 'For dress fitting at the atelier',
      instruction: 'Save the QR codes below and show them when you arrive at the atelier to start fitting each dress directly',
      downloadOne: 'Save',
      downloadAll: 'Save All QR Codes',
      done: 'Done',
    },
    whatsapp: {
      title: 'Book Measurement Appointment',
      trialCostText: 'Dress trial cost: 100 EGP per dress',
      success: 'Your request was sent successfully! WhatsApp notification was delivered and we will contact you to confirm.',
      errorSave: 'Error saving reservation. Check your connection and try again.',
      errorGeneric: 'Failed to send your request. Please try again.',
      fullName: 'Full name *',
      namePlaceholder: 'e.g. Nora Ahmed',
      phone: 'Phone number *',
      phonePlaceholder: '01012345678',
      weight: 'Weight (kg)',
      weightPlaceholder: 'e.g. 60',
      height: 'Height (cm)',
      heightPlaceholder: 'e.g. 165',
      trialDate: 'Trial date *',
      rentDate: 'Desired rent date *',
      time: 'Preferred time *',
      notes: 'Additional notes (optional)',
      notesPlaceholder: 'Any extra details...',
      sending: 'Sending...',
      confirm: 'Confirm & Book',
      dateBlockedMessagePrefix: 'The dress',
      dateBlockedHint: 'Please choose another date or contact the atelier.',
      dateBlockedOk: 'OK, I will choose another date',
    },
    sales: {
      loginTitle: 'Sales Login',
      loginSubtitle: 'Enter passcode to access the sales dashboard.',
      loginButton: 'Enter Dashboard',
      loginError: 'Invalid passcode, please try again.',
      dashboardTitle: 'Sales Dashboard',
      dashboardSubtitle: 'You can confirm or delete orders here.',
      passcodeLabel: 'Passcode *',
      passcodePlaceholder: 'e.g. 1234',
      brandPill: 'Sales',
      pending: 'Pending Orders',
      confirmed: 'Confirmed Orders',
      noReservations: 'No orders to display.',
      backToStore: 'Back to Store',
      confirmSuccess: 'Reservation confirmed successfully.',
      confirmFail: 'Failed to confirm reservation. Try again.',
      deleteSuccess: 'Order deleted successfully.',
      deleteFail: 'Failed to delete order. Try again.',
    },
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem('mary_lang') || DEFAULT;
    } catch {
      /* ignore localStorage read errors */
      return DEFAULT;
    }
  });

  useEffect(() => {
    try { localStorage.setItem('mary_lang', lang); } catch { /* ignore localStorage write errors */ }
    document.documentElement.lang = lang === 'ar' ? 'ar' : 'en';
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (path, ...args) => {
    const parts = path.split('.');
    let cur = TRANSLATIONS[lang] || TRANSLATIONS[DEFAULT];
    for (const p of parts) {
      if (cur && Object.prototype.hasOwnProperty.call(cur, p)) cur = cur[p];
      else { cur = null; break; }
    }
    if (typeof cur === 'function') return cur(...args);
    return cur ?? path;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
};
